version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.6.9-management
  ruby-invoices:
    build: ./ruby-invoices
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
  proxyservice:
    build: ./proxyservice
    ports:
      - "3000:3000"
      - "9090:9090"
    depends_on:
      - rabbitmq
      - ruby-invoices

