// Code generated by go-swagger; DO NOT EDIT.

/*
Package server ClientProxyService
A proxy service acquiring information from RabbitMQ RPC Queue


    Schemes:
      http
    Host: localhost:8080
    BasePath: /api/v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package server
